// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Graduation_Project.Models;

public partial class Final_ProjectContext : DbContext
{
    public Final_ProjectContext(DbContextOptions<Final_ProjectContext> options)
        : base(options)
    {
    }
    public virtual DbSet<SHORELINES_1986_2100> SHORELINES_1986_2100s { get; set; }

    public virtual DbSet<SHORELINE_2023_AFTER> SHORELINE_2023_AFTERs { get; set; }

    public virtual DbSet<SHORELINE_2023_CVI_1KM> SHORELINE_2023_CVI_1KMs { get; set; }

    public virtual DbSet<SHORELINE_2023_POINTS_100M> SHORELINE_2023_POINTS_100Ms { get; set; }

    public virtual DbSet<SHORELINE_2023_SEGMENTED_PROJECT> SHORELINE_2023_SEGMENTED_PROJECTs { get; set; }

    public virtual DbSet<UserLocation> UserLocations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SHORELINES_1986_2100>(entity =>
        {
            entity.HasKey(e => e.OBJECTID).HasName("PK__SHORELIN__F4B70D85F5D05FD7");

            entity.ToTable("SHORELINES_1986_2100");

            entity.HasIndex(e => e.Shape, "FDO_Shape");

            entity.Property(e => e.Shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2023_AFTER>(entity =>
        {
            entity.HasKey(e => e.OBJECTID).HasName("PK__SHORELIN__F4B70D855E9F4AC8");

            entity.ToTable("SHORELINE_2023_AFTER");

            entity.HasIndex(e => e.Shape, "FDO_Shape");

            entity.Property(e => e.CVI_Classify).HasMaxLength(255);
            entity.Property(e => e.EPR_Category).HasMaxLength(255);
            entity.Property(e => e.Shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2023_CVI_1KM>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E632B67F7F4E");

            entity.ToTable("SHORELINE_2023_CVI_1KM");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.cvi_classify).HasMaxLength(255);
            entity.Property(e => e.epr_category).HasMaxLength(255);
            entity.Property(e => e.shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2023_POINTS_100M>(entity =>
        {
            entity.HasKey(e => e.OBJECTID).HasName("PK__SHORELIN__F4B70D856E626B32");

            entity.ToTable("SHORELINE_2023_POINTS_100M");

            entity.HasIndex(e => e.Shape, "FDO_Shape");

            entity.Property(e => e.Coastal_Slope).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Current_Position_X).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Current_Position_Y).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Elevation).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.LRR).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.NSM).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Sea_Level_Rise_Trend_mm_year).HasColumnType("numeric(38, 8)");
            entity.Property(e => e.Shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<SHORELINE_2023_SEGMENTED_PROJECT>(entity =>
        {
            entity.HasKey(e => e.objectid).HasName("PK__SHORELIN__5242E632AE2817F0");

            entity.ToTable("SHORELINE_2023_SEGMENTED_PROJECT");

            entity.HasIndex(e => e.shape, "FDO_shape");

            entity.Property(e => e.date_).HasMaxLength(255);
            entity.Property(e => e.shape).HasColumnType("geometry");
        });

        modelBuilder.Entity<UserLocation>(entity =>
        {
            entity.HasIndex(e => e.Account_Id, "IX_UserLocations_Account_Id");

            entity.Property(e => e.shape).IsRequired();

        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}