// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace Graduation_Project.Models;

public partial class UserLocation
{
    public int Id { get; set; }

    public Geometry shape { get; set; }

    public int? Account_Id { get; set; }

}